name: Solar Sytem Workflow
on:
    workflow_dispatch: 
    push:
        branches:
        - main
        - 'feature/*'
env:
    MONGO_URI: 'mongodb+srv://superCluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
jobs:
    unit-testing:
        name: Unit-testing
        runs-on: ubuntu-latest
        steps:
        - name: checkout action
          uses: actions/checkout@v6
        - name: Install node js
          uses: actions/setup-node@v6
          with:
            node-version: 24
        - name: Install dependencies
          run: npm install
        - name: unit testing
          run: npm test
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mpcha-Test-Result
            path: test-results.xml